### ISSUE TITLE
Analysis the failed reason of `alphanet_openzeppelin_test`

### ISSUE THREAD

**Issue by Flouse** [godwokenrises/godwoken-tests#175]
https://github.com/nervosnetwork/godwoken-tests/actions/workflows/alphanet_openzeppelin_test.yml

**Comment by gpBlockchain** [comment]
本地复现不出来，加了一些日志逻辑
- 打印 send tx 和gas的rpc调用信息
- 打印 异常rpc的调用信息
https://github.com/gpBlockchain/test-action/runs/8129240674?check_suite_focus=true#logs
