### ISSUE TITLE
Issue with `ethers > 5.6.1`

### ISSUE THREAD

**Issue by ShookLyngs** [godwokenrises/godwoken-tests#181]
### Description
Currently, Hardhat and Ethers has an issue with "reverted info".
For more detailed description please check the reference link below. 

The issue has been temporarily fixed. 
But since it's not completely solved, we still need to **observe** till the issue is completely fixed by Ethers team.

### References
- https://github.com/nervosnetwork/godwoken-tests/pull/180

**Comment by keroro520** [comment]
This issue should be fixed by https://github.com/nervosnetwork/godwoken-web3/pull/512 which is included in Godwoken-Web3 [v1.8.0](https://github.com/nervosnetwork/godwoken-web3/releases/tag/v1.8.0).

**Comment by keroro520** [comment]
https://github.com/godwokenrises/godwoken-tests/issues/181#issuecomment-1260362975
